---

- name: download public signing key
  shell: rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

- name: make elastic repository
  copy: >
    src=roles/elasticsearch/files/es.repo
    dest=/etc/yum.repos.d/es.repo
    owner=root
    group=root
    mode=0644

- name: install elasticsearch
  yum: > 
    name=elasticsearch
    state=latest
    enablerepo=elasticsearch
  notify:
    - es install

- name: copy elasticsearch basic setting
  copy: >
    src=roles/elasticsearch/files/elasticsearch.yml
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=elasticsearch
    mode=0750

- name: insert nodes ip
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    line="{{ item }}"
  with_items:
    - 'node.master: true'
    - 'node.date:   false'
  notify:
    - es restart
