---

- name: download public signing key
  shell: rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

- name: make elastic repository
  copy: >
    src=roles/elasticsearch/files/es.repo
    dest=/etc/yum.repos.d/es.repo
    owner=root
    group=root
    mode=0644

- name: install elasticsearch
  yum: > 
    name=elasticsearch
    state=latest
    enablerepo=elasticsearch
  notify:
    - es install

- name: copy elasticsearch basic setting
  copy: >
    src=roles/elasticsearch/files/elasticsearch.yml
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=elasticsearch
    mode=0750

- name: insert nodes ip
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    line="{{ item }}"
  with_items:
    - 'node.master: true'
    - 'node.data:   false'
  when: node == "master"
  notify:
    - es restart

- name: insert nodes ip
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    line="{{ item }}"
  with_items:
    - 'node.master: true'
    - 'node.data:   true'
  when: node == "search"
  notify:
    - es restart

- name: insert nodes ip
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    line="{{ item }}"
  with_items:
    - 'node.master: false'
    - 'node.data:   true'
  when: node == "data"
  notify:
    - es restart

- name: add hosts
  lineinfile: >
    dest=/etc/hosts
    line="{{ item }}"
  with_items:
    - '192.168.33.21 deves01'
    - '192.168.33.22 deves02'
    - '192.168.33.23 deves03'
    - '192.168.33.24 deves04'
    - '192.168.33.24 deves05'

- name: install plugin
  shell: bin/plugin install "{{ item }}" chdir=/usr/share/elasticsearch
  with_items:
    - analysis-icu
    - analysis-kuromoji 
    - mobz/elasticsearch-head
    - royrusso/elasticsearch-HQ
    - license
    - marvel-agent
