Vagrant.configure(2) do |config|
  # config.vbguest.auto_update = false

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define :svr01 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.51", auto_config: false
    ### vbox name
    server.vm.hostname = 'elastic-dev'
    ### box setting
    server.vm.box = "bento/ubuntu-16.04"
    ### bug fix
    server.vm.provision 'shell', inline: "ifconfig enp0s8 192.168.33.51" 
    server.vm.provision 'shell', inline: "sed -i 's/exit\ 0/ifconfig\ enp0s8\ 192\.168\.33\.51/g' /etc/rc.local" 
    server.vm.provision 'shell', inline: "echo 'exit 0' >> /etc/rc.local" 
    server.vm.provision 'shell', inline: "chmod 644 /home/vagrant/.ssh/authorized_keys" 
 end

  config.vm.provider "virtualbox" do |vb|
    ### vagrant hostname 
    vb.name = "elastic-dev"
    vb.customize ['modifyvm', :id,"--memory", 2048]
    vb.customize ['modifyvm', :id,"--natdnshostresolver1", "on"]
    vb.customize ['modifyvm', :id,"--natdnsproxy1", "on"]
  end  
 
  ### settitng of synced_folder
  config.vm.synced_folder "../../", "/opt/elastic", \
    :create => true, \
    :owner  => 'root', \
    :group  => 'root', \
    :mount_options => ['dmode=755,fmode=755'] 

  config.vm.provision :shell, inline: "/bin/bash /opt/elastic/opsfiles/vagrant/provision.sh vagrant"

end
