Vagrant.configure("2") do |config|
  # config.vm.box = "bento/centos-6.7"
  # config.vbguest.auto_update = false

  config.vm.define :svr01 do |server|
    server.vm.network :private_network, ip: "192.168.33.21"
    server.vm.hostname = 'deves01'
    server.vm.box = "bento/centos-6.7"
  end
  config.vm.define :svr02 do |server|
    server.vm.network :private_network, ip: "192.168.33.22"
    server.vm.hostname = 'deves02'
    server.vm.box = "bento/centos-6.7"
  end
  config.vm.define :svr03 do |server|
    server.vm.network :private_network, ip: "192.168.33.23"
    server.vm.hostname = 'deves03'
    server.vm.box = "bento/centos-6.7"
  end

  config.vm.synced_folder "../", "/develop/dev.es", \
    :create => true, \
    :owner => 'root', \
    :group => 'root', \
    :mount_options => ['dmode=755,fmode=755']

  config.vm.provider :virtualbox do |vb|
    # vb.name = "dev.es"
    vb.customize ["modifyvm", :id, "--memory", 512]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision :shell, :path => "ssh/init.sh"

end
