---
- name: install mysql
  apt: pkg="{{item}}" update_cache=yes
  with_items:
  - mysql-server

- name: my.conf config
  copy: >
    src=roles/mysql/templates/my.cnf.j2
    dest=/etc/mysql/my.cnf
    backup=yes
    group=root
    owner=root
    mode=0644

- name: mysqld config
  copy: >
    src=roles/mysql/templates/mysql.conf.d_mysqld.cnf.j2
    dest=/etc/mysql/mysql.conf.d/mysqld.cnf
    backup=yes
    group=root
    owner=root
    mode=0644

- name: force restart
  shell: sleep 20 && /etc/init.d/mysql restart

- name: create mysql_user adm
  mysql_user: >
    name=db_adm
    host=localhost
    password={{ mysql.password_db_adm }}
    priv=*.*:ALL,GRANT
    state=present

- name: change permision
  file: >
    path=/var/lib/mysql-files
    state=directory
    mode=0777
    group=root
    owner=root
    force=yes

- name: create mysql_user lbs-mypage
  mysql_user: >
    name=lbs_mypage_dbuser
    host=%
    password={{ mysql.password_lbs_mypage_dbuser }}
    priv=*.*:ALL
    state=present
  when: node == 'lbs-mypage'
  notify: mysql restart

- name: create mysql_user crawler-javpop
  mysql_user: >
    name=crawler_javpop_dbuser
    host={{ item }}
    password={{ mysql.password_crawler_javpop_dbuser }}
    priv=*.*:ALL
    state=present
  with_items:
    - 192.168.0.0/255.255.0.0
    - localhost
  when: node == 'crawler-javpop'
  notify: mysql restart

- name: setting root user
  copy: >
    src=roles/mysql/files/my.cnf
    dest=/root/.my.cnf
    backup=yes
    group=root
    owner=root
    mode=0600

- name: setting root password
  replace: >
    dest=/root/.my.cnf
    regexp='ROOT_PASSWORD'
    replace={{ mysql.password_root }}
