---
#
# roles/nodejs/tasks/main.yml
#
- name: install package to https method and CA certificates
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
  - apt-transport-https
  - ca-certificates

- name: Add the new GPG key
# - name: hoge
#   apt_key: >
#     url={{ docker.kerserver }}
#     id={{ docker.id }}
  shell: apt-key adv \
         --keyserver {{ docker.keyserver }}:80 \
         --recv-keys {{ docker.id }}


- name: get repository
  lineinfile: >
    dest=/etc/apt/sources.list.d/docker.list
    line=" deb {{ docker.repo }} {{ docker.version }} main"
    state=present
    create=yes

- name: apt-get update
  apt: upgrade=dist

- name: install docker
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
  - docker-engine
