---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: debian-7.8
- name: centos-7.0
- name: centos-6.6
- name: centos-5.9
- name: fedora-21
- name: amazon-2014.09.1
  driver:
    name: ec2
    aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] || 'AWS_ACCESS_KEY' %>
    aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] || 'AWS_SECRET_KEY' %>
    aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] || 'AWS_SSH_KEY_ID' %>
    region: us-east-1
    image_id: ami-b66ed3de
    flavor_id: m3.medium
    ebs_volume_size: 8
    ebs_delete_on_termination: true
    ebs_device_name: /dev/sda
    username: ec2-user

suites:
- name: default
  run_list: ["recipe[timezone-ii]"]
  attributes:
    tz: "Pacific/Tongatapu" # "TOT"
