Vagrant.configure("2") do |config|
  # config.vm.box = "bento/centos-6.7"
  # config.vbguest.auto_update = false

  config.vm.define :svr1 do |server|
    server.vm.network :private_network, ip: "192.168.33.21"
    server.vm.hostname = 'deves1'
    server.vm.box = "bento/centos-6.7"
  end
  config.vm.define :svr2 do |server|
    server.vm.network :private_network, ip: "192.168.33.22"
    server.vm.hostname = 'deves2'
    server.vm.box = "bento/centos-6.7"
  end
  config.vm.define :svr3 do |server|
    server.vm.network :private_network, ip: "192.168.33.23"
    server.vm.hostname = 'deves3'
    server.vm.box = "bento/centos-6.7"
  end
  config.vm.define :svr4 do |server|
    server.vm.network :private_network, ip: "192.168.33.24"
    server.vm.hostname = 'deves4'
    server.vm.box = "bento/centos-6.7"
  end
  config.vm.define :svr5 do |server|
    server.vm.network :private_network, ip: "192.168.33.25"
    server.vm.hostname = 'deves5'
    server.vm.box = "bento/centos-6.7"
  end
  config.vm.define :svr6 do |server|
    server.vm.network :private_network, ip: "192.168.33.26"
    server.vm.hostname = 'deves6'
    server.vm.box = "bento/centos-6.7"
  end

  config.vm.synced_folder "../", "/develop/dev.es", \
    :create => true, \
    :owner => 'root', \
    :group => 'root', \
    :mount_options => ['dmode=755,fmode=644']

  config.vm.provider :virtualbox do |vb|
    # vb.name = "dev.es"
    vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.omnibus.chef_version=:latest
  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = "./es/cookbooks"
    chef.roles_path = "es/roles"
    chef.add_role "common"
  end

  config.vm.provision :shell, :path => "../env-install_1.x.sh"

end
