Vagrant.configure("2") do |config|
  # config.vm.box = "bento/centos-6.7"
  # config.vbguest.auto_update = false

  config.vm.define :svr1 do |server|
    server.vm.network :private_network, ip: "192.168.33.21"
    server.vm.hostname = 'dev.es.1'
    server.vm.box = "bento/centos-6.7"
  end
  config.vm.define :svr2 do |server|
    server.vm.network :private_network, ip: "192.168.33.22"
    server.vm.hostname = 'dev.es.2'
  # config.vm.box = "bento/centos-6.7"
    server.vm.box = "bento/centos-6.7"
  end

  config.vm.synced_folder "../", "/develop/dev.es", \
    :create => true, \
    :owner => 'root', \
    :group => 'root', \
    :mount_options => ['dmode=755,fmode=644']

  config.vm.provider :virtualbox do |vb|
    # vb.name = "dev.es"
    vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

#   config.vm.provision :shell, :inline => <<SCRIPT
#     # yum install -y https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chefdk-0.4.0-1.x86_64.rpm
# SCRIPT
  # config.vm.provision :shell, :path => "../env-install.sh"

  config.omnibus.chef_version=:latest
  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = "./es/cookbooks"
    chef.roles_path = "es/roles"
    chef.add_role "common"
  end
end
