---

- hosts: es-master
  roles:
    - common
    - java
    - elasticsearch
    - kibana

- hosts: es-search
  roles:
    - common
    - java
    - elasticsearch
    - td-agent

- hosts: es-data
  roles:
    - common
    - java
    - elasticsearch
