---
#
# roles/user/tasks/main.yml
#
- name: create group
  group: >
    name={{ user.user_group }}

- name: create user
  user: >
    state=present
    name={{ user.user_name }}
    group={{ user.user_group }}
    password={{ user.password }}
    shell=/bin/bash

- name: setting NOPASSWORD
  lineinfile: >
    dest=/etc/sudoers
    backup=yes
    line='{{ user.user_name }} ALL=(ALL) NOPASSWD: ALL'
  ignore_errors: true

- name: mkdir '.ssh'
  file: >
    state=directory
    path=/home/{{ user.user_name }}/.ssh
    owner={{ user.user_name }}
    group={{ user.user_group }}
    mode=0700

- name: copy public key ( upuser )
  copy: >
    src=roles/upuser/files/id_rsa-hejda-upuser.pub
    dest=/home/{{ user.user_name }}/.ssh/authorized_keys
    owner={{ user.user_name }}
    group={{ user.user_group }}
    mode=0644

- name: copy secret key ( upuser )
  copy: >
    src=roles/upuser/files/id_rsa-hejda-upuser
    dest=/home/{{ user.user_name }}/.ssh/id_rsa-hejda-upuser
    owner={{ user.user_name }}
    group={{ user.user_group }}
    mode=0600

- name: ssh config ( upuser )
  copy: >
    src=roles/upuser/files/config
    dest=/home/{{ user.user_name }}/.ssh/config
    owner={{ user.user_name }}
    group={{ user.user_group }}
    mode=0644

- name: copy and setting public key from vagrant
  shell: cp /home/vagrant/.ssh/authorized_keys              \
            /home/{{ user.user_name }}/.ssh/authorized_keys \
         &&                                                 \
         chown {{ user.user_name }}.{{ user.user_group }}    \ 
         /home/{{ user.user_name }}/.ssh/authorized_keys
  when: node == "vagrant"  
