---

- name: check java rpm
  stat: path={{ jdk.rpm_path}}
  register: java_exists

- name: wget java.rpm
  command: >
    wget -O {{ jdk.rpm_path }} --no-check-certificate --no-cookies
    --header "Cookie: oraclelicense=accept-securebackup-cookie" "{{ jdk.dl_url}}"
  when: java_exists.stat.md5 is not defined

- name: install rpm
  command: >
    rpm -Uhv {{ jdk.rpm_path }}
