Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-6.7"
  # config.vbguest.auto_update = false

  config.vm.define :deves01 do |server|
    server.vm.network :private_network, ip: "192.168.33.21"
    server.vm.hostname = 'deves01'
  end
  # config.vm.define :deves02 do |server|
  #   server.vm.network :private_network, ip: "192.168.33.22"
  #   server.vm.hostname = 'deves02'
  # end
  # config.vm.define :deves03 do |server|
  #   server.vm.network :private_network, ip: "192.168.33.23"
  #   server.vm.hostname = 'deves03'
  # end
  # config.vm.define :deves04 do |server|
  #   server.vm.network :private_network, ip: "192.168.33.24"
  #   server.vm.hostname = 'deves04'
  # end

  config.vm.provider :virtualbox do |vb|
    # vb.name = "dev.es"
    vb.customize ["modifyvm", :id, "--memory", 512]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.synced_folder "../../", "/opt/dev.es", \
    :create => true, \
    :owner => 'root', \
    :group => 'root', \
    :mount_options => ['dmode=755,fmode=755']

  config.vm.provision :shell, :path => "ssh/init.sh"
  # config.vm.provision :shell, :path => "env-basic-centos.sh"
  # config.vm.provision :shell, :path => "env-install_es_2.x.sh"
  # config.vm.provision :shell, :path => "env-install_kibana_4.5.sh"

end
