Vagrant.configure(2) do |config|
  # config.vbguest.auto_update = false

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define :es01 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.21", auto_config: false
    ### box setting
    server.vm.box = "bento/ubuntu-16.04"
    ### vbox name
    server.vm.hostname = 'es01'
    ### server setting
    config.vm.provider "virtualbox" do |vb|
      vb.name = "es01"
      vb.customize ["modifyvm", :id, "--memory", 512]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    ### bug fix
    server.vm.provision 'shell', inline: "ifconfig enp0s8 192.168.33.21" 
    server.vm.provision 'shell', inline: "sed -i 's/exit\ 0/ifconfig\ enp0s8\ 192\.168\.33\.21/g' /etc/rc.local" 
    server.vm.provision 'shell', inline: "echo 'exit 0' >> /etc/rc.local" 
    server.vm.provision 'shell', inline: "chmod 644 /home/vagrant/.ssh/authorized_keys" 
  end

  # config.vm.define :es02 do |server|
  #   ### determined specific IP.
  #   server.vm.network "private_network", ip: "192.168.33.22", auto_config: false
  #   ### box setting
  #   server.vm.box = "bento/ubuntu-16.04"
  #   ### vbox name
  #   server.vm.hostname = 'es02'
  #   ### server setting
  #   config.vm.provider "virtualbox" do |vb|
  #     vb.name = "es02"
  #     vb.customize ["modifyvm", :id, "--memory", 1024]
  #     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  #   end
  #   ### bug fix
  #   server.vm.provision 'shell', inline: "ifconfig enp0s8 192.168.33.22" 
  #   server.vm.provision 'shell', inline: "sed -i 's/exit\ 0/ifconfig\ enp0s8\ 192\.168\.33\.22/g' /etc/rc.local" 
  #   server.vm.provision 'shell', inline: "echo 'exit 0' >> /etc/rc.local" 
  #   server.vm.provision 'shell', inline: "chmod 644 /home/vagrant/.ssh/authorized_keys" 
  # end
 
  ### settitng of synced_folder
  config.vm.synced_folder "../../", "/opt/es-cluster", \
    :create => true, \
    :owner  => 'vagrant', \
    :group  => 'vagrant', \
    :mount_options => ['dmode=755,fmode=755'] 

  config.vm.provision :shell, inline: "/bin/bash /opt/es-cluster/opsfiles/vagrant/provision.sh local"

end
