---
#
# roles/java/tasks/main.yml
#
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest
  # when: node == 'spring-boot'

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'
  # when: node == 'spring-boot'

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  # when: node == 'spring-boot'

- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
  # when: node == 'spring-boot'
